# Generated by Django 4.1 on 2024-11-07 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("burgers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="franchise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=2000)),
                ("address", models.CharField(max_length=2000)),
                ("owner", models.CharField(max_length=100)),
            ],
        ),
    ]
